WS2-1221 - Added Why Choose ASU fields (and backend processing) to De…
ASUWebPlatforms/webspark-module-asu_degree_rfi pull request #52
Opened 2022-12-13 23:25 UTC by bjdevil21

…gree Details content type to allow customization.

2022-12-13 23:26 UTC, bjdevil21 commented
I did leave some of the degree detail form display's weights as they were in my commit, but that shouldn't break anything.

2022-12-14 16:02 UTC, mlsamuelson requested changes

2022-12-14 17:07 UTC, bjdevil21 reviewed
I've removed the apostrophes and committed the change.

2022-12-14 17:08 UTC, bjdevil21 commented on config/install/core.entity_form_display.node.degree_detail_page.default.yml
> +        description: 'The following fields allow content creators to override the default "Why Choose ASU?" content as contained in the ASU Web standards'' Degree Detail pages.'
Change applied.

2022-12-14 17:57 UTC, mlsamuelson approved these changes

2022-12-14 17:57 UTC, merged